#+title: Interfaces
#+options: toc:nil
#+subtitle: SystemVerilog Series
#+date:
#+author: =@nebu=
#+include: ./org_header.org

# * Hooking it up
# #+begin_src systemverilog
#   dut dut_i (
#     .clk,
#     .rst,
#     .data_in,
#     .data_out
#   )

#   master master_i (
#     .clk,
#     .rst,
#     .data_in (some_stream),
#     .data_out (data_in)
#   );

#   slave slave_i (
#     .clk,
#     .rst,
#     .data_in (data_out),
#     .data_out (another_stream)
#   )
# #+end_src

* What is an interface?
- "At its lowest level, an interface is a named bundle of nets or
  variables." -- IEEE 1800-2012 25.2.

- Here's an example of what one looks like:
  #+begin_src systemverilog
    interface axi_stream;
      logic clk;
      logic rst;
      logic valid;
      logic ready;
      // ... and so on
    endinterface
  #+end_src


* Why is it useful?
- Consider the port list of this DUT that uses the AXI Stream protocol for I/O:
  #+begin_src systemverilog
    module dut (
      input logic       clk,
      input logic       rst,
      // Input stream
      input logic       valid_i,
      input logic [7:0] data_i,
      output logic      ready_i,
      // Output stream
      output logic      valid_o,
      output logic      data_o,
      input logic       ready_o
    );
  #+end_src

- This still doesn't implement a majority of the AXI Stream protocol...


* Now, consider hooking that DUT up
#+LATEX: \begin{columns}\begin{column}{0.5\textwidth}
- There's a master of the DUT, and a slave of the DUT.
- These components have their own AXI Streams.
- Naming these signals is getting ambiguous -- lots of potential for error.

#+begin_src systemverilog
  dut dut_i (
    //...
    .valid_i,
    .data_i,
    //...
  );
#+end_src
#+LATEX: \end{column} \begin{column}{0.5\textwidth}
#+begin_src systemverilog
  master master_i (
    //...
    .valid_o (valid_i),
    .data_o  (data_i),
    .ready_o (ready_i)
  );
  slave slave_i (
    //...
    .valid_i (valid_o),
    .data_i  (data_o),
    //...
  );
#+end_src

#+LATEX: \end{column}\end{columns}

* Visually
[[./images/interface_diagram.pdf]]

* With an interface...
- Encapsulates the signals associated with a logical "stream" into a
  bundle.
- Turning a set of names that are often used together into a single
  name makes life much easier, and RTL less error-prone.
- Verification benefits: interfaces can include tasks, functions,
  assertions.

* Specifying directions: =modport=
- Think back to the syntax at the beginning:
  #+begin_src systemverilog
    interface axi_stream;
      logic clk;
      logic rst;
      logic valid;
      logic ready;
      // ... and so on
    endinterface
  #+end_src
- This doesn't specify port directions!
- Port directions are different (typically opposite) depending on
  whether the module you're writing is the master or the slave.


* Visually
[[./images/interface_modports.pdf]]

* For AXI Stream (Handshaking)
- Without defining and using =modport='s, all interface signals are
  =inout= (bad).

  #+begin_src systemverilog
    interface axi_handshake;
      logic valid;
      logic ready;

      modport master (
        output valid,
        input  ready
      );

      modport slave (
        input  valid,
        output ready
      );
    endinterface
  #+end_src


* Usage
#+begin_src systemverilog
  module module_a (
    input logic       clk,
    input logic       rst,
    axi_stream.master data_out,
  );

  module module_b (
    input logic      clk,
    input logic      rst,
    axi_stream.slave data_in,
  );
#+end_src

To instantiate:
#+begin_src systemverilog
  axi_stream itf;
  module_a module_a_i (.clk, .rst, .data_out(itf));
  module_b module_b_i (.clk, .rst, .data_in(itf));
#+end_src


* Parametrizable Interfaces

* Interface Ports

* Verification using interfaces

# * Clocking Blocks in Interfaces # move to clocking-block.org
